version: '3.4'

services:
  lb:
    image: dockercloud/haproxy
    ports:
      - 80:80
      - 1936:1936
    links:
      - apache
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frontend-network

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes: 
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - backend-network
    restart: always

  apache:
    build: ./apache
    depends_on: 
      - mysql
    networks:
      - frontend-network
      - backend-network
    restart: always

volumes:
   mysql_data:

networks:
   frontend-network:
   backend-network:
